### ISSUE TITLE
Arch Linux: No input or output devices listed

### ISSUE THREAD

**Issue by samwho** [arirusso/unimidi#13]
I realise that this error is similar to other existing errors but the solutions all appear to be for OSX machines, so I thought I'd open up a new issue to troubleshoot this on Arch :)

I had to install alsa-rawmidi, midi-jruby and midi-winmm to actually require the unimidi gem in my code.

Running "unimidi list" at the command line returns:

```
input:
output:
```

I'm running a software midi synth. I tried with timidity and qsynth and I get the same result with both.

Am I doing something wrong? :)

**Comment by ericwilk** [comment]
Hmm, strange -- it doesn't list the programs I have open when I load the module, only a bunch of virtual devices. I'm not going straight through ALSA though; I'm using JACK on top of that. I'm assuming that's the reason why. aconnect -il/ol still gives me what I need, so I'll probably fiddle around with this a bit. I'm assuming if I can get the client ID I can somehow get this working.
