### ISSUE TITLE
No MIDI inputs or outputs listed OSX 10.6.8

### ISSUE THREAD

**Issue by aaronats** [arirusso/unimidi#16]
Hi Ari,

I am fairly new to messing around with MIDI IO in general and I am basically attempting to run the output.rb in the examples directory out of the built-in speakers on my mac. I am unable to get a list of any MIDI device inputs or outputs.

In irb the following returns an empty list

> @output = UniMIDI::Output.gets
> Select a MIDI output...

Same thing for input. Any help would be greatly appreciated!

Thanks,
Aaron

**Comment by daqo** [comment]
I have the same issue in Yosemite. Any workaround?

**Comment by arirusso** [comment]
Have you configured IAC ? http://tx81z.blogspot.com/2011/06/osx-unimidi-and-midi-patch-bay.html

**Comment by daqo** [comment]
Thanks. Now I can select the output device. Though when I run sample code, there would be no sound even if GarageBand is open. 

Sample code:

```require 'rubygems'
require 'unimidi'
require 'pry'

notes = [36, 40, 43, 48, 52, 55, 60, 64, 67] # C E G arpeggios
duration = 0.1
output = UniMIDI::Output.open(:first)
output.open do |output|

  notes.each do |note|
    output.puts(0x90, note, 100) # note on message
    sleep(duration)  # wait
    output.puts(0x80, note, 100) # note off message
  end
end```

**Comment by arirusso** [comment]
It's likely your GarageBand configuration-- I don't use that program so it'd be difficult to be of much help. Might be something to post on stackoverflow

**Comment by daqo** [comment]
But shouldn't the sample problem work even if GarageBand is not open?

```
require 'rubygems'
require 'unimidi'

notes = [36, 40, 43, 48, 52, 55, 60, 64, 67] # C E G arpeggios
duration = 0.1
output = UniMIDI::Output.open(:first)
output.open do |output|
  notes.each do |note|
    output.puts(0x90, note, 100) # note on message
    sleep(duration)  # wait
    output.puts(0x80, note, 100) # note off message
  end
end
```

**Comment by arirusso** [comment]
Is there any indication that it's not working?

**Comment by daqo** [comment]
It's successfully quitting but there is no sound coming out.

**Comment by arirusso** [comment]
This program doesn't make sound-- it ostensibly sends MIDI messages to a program that makes sound according to those messages. 

I encourage you to post questions on stackoverflow!  you'll be able to get help with this there

**Comment by daqo** [comment]
Ok, thank you so much for your help. If I found a workaround I will post it here.

**Comment by daqo** [comment]
A simple restart and reopening Garageband solved the issue for me. 

Thank you.
